[[redirects]]
	from = "/app"
	to = "http://app.sahay.us/"

[[redirects]]
	from = "/branding"
	to = "https://www.behance.net/gallery/122334161/Sahay-Consolidating-the-Medical-System"

[[redirects]]
	from = "/design"
	to = "https://www.behance.net/gallery/122334161/Sahay-Consolidating-the-Medical-System"

[[redirects]]
	from = "/figma"
	to = "https://www.figma.com/file/tsNVp7huKBsmi62toTGu4r/Sahay-Hack-JIT?node-id=0%3A1"

[[redirects]]
  from = "/download"
  to = "https://drive.google.com/drive/folders/13sPrB17XOI8oZmGYhXsvgLVDajyb7Cdx?usp=sharing"


[[redirects]]
	from = "/*"
	to = "index.html"	
	status = 200
